<?php

class Helper_Country {
    /**
     * Get country list
     *
     * @return array
     */
    public static function getList() {
		$countries = Kohana::$config->load('project.countries');
		$returnlist = array();
		foreach($countries as $c) {
			$returnlist[$c] = Helper_Message::get('country.' . $c);
		}
		return $returnlist;
	}

    /**
     * @param $iso
     * @return mixed
     */
    public static function countryName($iso) {
		return Arr::get(self::getList(), $iso, null);
	}

    /**
     * @param $name
     * @return mixed
     */
    static function getCountryCodeByName($name) {
        $laender = array("AD" => "Andorra",
                          "AE" => "Vereinigte Arabische Emirate",
                          "AF" => "Afghanistan",
                          "AG" => "Antigua und Barbuda",
                          "AI" => "Anguilla",
                          "AL" => "Albanien",
                          "AM" => "Armenia",
                          "AN" => "Niederländische Antillen",
                          "AO" => "Angola",
                          "AQ" => "Antarktis",
                          "AR" => "Argentinen",
                          "AS" => "Amerikanisch-Samoa",
                          "AT" => "Österreich",
                          "AU" => "Australien",
                          "AW" => "Aruba",
                          "AZ" => "Azerbaijan",
                          "BA" => "Bosnien und Herzegovina",
                          "BB" => "Barbados",
                          "BD" => "Bangladesh",
                          "BE" => "Belgien",
                          "BF" => "Burkina Faso",
                          "BG" => "Bulgarien",
                          "BH" => "Bahrain",
                          "BI" => "Burundi",
                          "BJ" => "Benin",
                          "BM" => "Bermuda",
                          "BN" => "Brunei Darussalam",
                          "BO" => "Bolivien",
                          "BR" => "Brasilien",
                          "BS" => "Bahamas",
                          "BT" => "Bhutan",
                          "BV" => "Bouvet Island",
                          "BW" => "Botswana",
                          "BY" => "Belarus",
                          "BZ" => "Belize",
                          "CA" => "Canada",
                          "CC" => "Cocos (Keeling) Islands",
                          "CD" => "Demokratische Republik Kongo",
                          "CF" => "Zentralafrika",
                          "CG" => "Kongo",
                          "CH" => "Schweiz",
                          "CI" => "Elfenbeinküste",
                          "CK" => "Cook Islands",
                          "CL" => "Chile",
                          "CM" => "Kamerun",
                          "CN" => "China",
                          "CO" => "Kolumbien",
                          "CR" => "Costa Rica",
                          "CS" => "Tschechoslowakei",
                          "CU" => "Kuba",
                          "CV" => "Kap Verde",
                          "CX" => "Christmas Island",
                          "CY" => "Zypern",
                          "CZ" => "Tschechische Republik",
                          "DE" => "Deutschland",
                          "DJ" => "Djibouti",
                          "DK" => "Dänemark",
                          "DM" => "Dominica",
                          "DO" => "Dominikanische Republik",
                          "DZ" => "Algerien",
                          "EC" => "Ecuador",
                          "EE" => "Estland",
                          "EG" => "Ägypten",
                          "EH" => "Westsahara",
                          "ER" => "Eritrea",
                          "ES" => "Spanien",
                          "ET" => "Äthiopien",
                          "FI" => "Finnland",
                          "FJ" => "Fiji",
                          "FK" => "Falklandinseln (Malvinas)",
                          "FM" => "Micronesien",
                          "FO" => "Faröer-Inseln",
                          "FR" => "Frankreich",
                          "FX" => "France, Metropolitan",
                          "GA" => "Gabon",
                          "GD" => "Grenada",
                          "GE" => "Georgien",
                          "GF" => "Französisch Guiana",
                          "GH" => "Ghana",
                          "GI" => "Gibraltar",
                          "GL" => "Grönland",
                          "GM" => "Gambia",
                          "GN" => "Guinea",
                          "GP" => "Guadeloupe",
                          "GQ" => "Äquatorialguinea",
                          "GR" => "Griechenland",
                          "GS" => "Südgeorgien und Südliche Sandwich-Inseln",
                          "GT" => "Guatemala",
                          "GU" => "Guam",
                          "GW" => "Guinea-Bissau",
                          "GY" => "Guyana",
                          "HK" => "Kong Hong",
                          "HM" => "Heard und Mc Donald Islands",
                          "HN" => "Honduras",
                          "HT" => "Haiti",
                          "HU" => "Ungarn",
                          "ID" => "Indonesien",
                          "IE" => "Irland",
                          "IL" => "Israel",
                          "IN" => "Indien",
                          "IO" => "British Indian Ocean Territory",
                          "IQ" => "Irak",
                          "IR" => "Iran (Islamische Republik)",
                          "IS" => "Island",
                          "IT" => "Italien",
                          "JM" => "Jamaika",
                          "JO" => "Jordanien",
                          "JP" => "Japan",
                          "KE" => "Kenya",
                          "KG" => "Kirgisien",
                          "KH" => "Kambodscha",
                          "KI" => "Kiribati",
                          "KM" => "Komoren",
                          "KN" => "Saint Kitts und Nevis",
                          "KP" => "Korea, Volksrepublik",
                          "KR" => "Korea",
                          "KW" => "Kuwait",
                          "KY" => "Kayman Islands",
                          "KZ" => "Kasachstan",
                          "LA" => "Laos",
                          "LB" => "Libanon",
                          "LC" => "Saint Lucia",
                          "LI" => "Liechtenstein",
                          "LK" => "Sri Lanka",
                          "LR" => "Liberia",
                          "LS" => "Lesotho",
                          "LT" => "Littauen",
                          "LU" => "Luxemburg",
                          "LV" => "Lettland",
                          "LY" => "Libyen",
                          "MA" => "Marokko",
                          "MC" => "Monaco",
                          "MD" => "Moldavien",
                          "MG" => "Madagaskar",
                          "MH" => "Marshall-Inseln",
                          "MK" => "Mazedonien, ehem. Jugoslawische Republik",
                          "ML" => "Mali",
                          "MM" => "Myanmar",
                          "MN" => "Mongolei",
                          "MO" => "Macao",
                          "MP" => "Nördliche Marianneninseln",
                          "MQ" => "Martinique",
                          "MR" => "Mauretanien",
                          "MS" => "Montserrat",
                          "MT" => "Malta",
                          "MU" => "Mauritius",
                          "MV" => "Malediven",
                          "MW" => "Malawi",
                          "MX" => "Mexico",
                          "MY" => "Malaysien",
                          "MZ" => "Mozambique",
                          "NA" => "Namibia",
                          "NC" => "Neu Kaledonien",
                          "NE" => "Niger",
                          "NF" => "Norfolk Island",
                          "NG" => "Nigeria",
                          "NI" => "Nicaragua",
                          "NL" => "Niederlande",
                          "NO" => "Norwegen",
                          "NP" => "Nepal",
                          "NR" => "Nauru",
                          "NU" => "Niue",
                          "NZ" => "Neuseeland",
                          "OM" => "Oman",
                          "PA" => "Panama",
                          "PE" => "Peru",
                          "PF" => "Französisch-Polynesien",
                          "PG" => "Papua Neuguinea",
                          "PH" => "Philippinen",
                          "PK" => "Pakistan",
                          "PL" => "Polen",
                          "PM" => "St. Pierre und Miquelon",
                          "PN" => "Pitcairn",
                          "PR" => "Puerto Rico",
                          "PT" => "Portugal",
                          "PW" => "Palau",
                          "PY" => "Paraguay",
                          "QA" => "Katar",
                          "RE" => "Reunion",
                          "RO" => "Rumänien",
                          "RU" => "Russische Föderation",
                          "RW" => "Ruanda",
                          "SA" => "Saudi Arabien",
                          "SB" => "Salomonen",
                          "SC" => "Seychellen",
                          "SD" => "Sudan",
                          "SE" => "Schweden",
                          "SG" => "Singapur",
                          "SH" => "St. Helena",
                          "SI" => "Slovenien",
                          "SJ" => "Svalbard und Jan Mayen Islands",
                          "SK" => "Slowakei",
                          "SL" => "Sierra Leone",
                          "SM" => "San Marino",
                          "SN" => "Senegal",
                          "SO" => "Somalia",
                          "SR" => "Surinam",
                          "ST" => "Sao Tome und Principe",
                          "SV" => "El Salvador",
                          "SY" => "Syrien, Arabische Republik",
                          "SZ" => "Swaziland",
                          "TC" => "Turk und Caicos-Inseln",
                          "TD" => "Tschad",
                          "TF" => "Französisches Südl.Territorium",
                          "TG" => "Togo",
                          "TH" => "Thailand",
                          "TJ" => "Tadschikistan",
                          "TK" => "Tokelau",
                          "TM" => "Turkmenistan",
                          "TN" => "Tunesien",
                          "TO" => "Tonga",
                          "TP" => "Ost-Timor",
                          "TR" => "Türkei",
                          "TT" => "Trinidad und Tobago",
                          "TV" => "Tuvalu",
                          "TW" => "Taiwan",
                          "TZ" => "Tansania, United Republic of",
                          "UA" => "Ukraine",
                          "UG" => "Uganda",
                          "GB" => "Großbritannien",
                          "US" => "USA",
                          "UM" => "Vereinigte Staaten, Minor Outlying Islands",
                          "UY" => "Uruguay",
                          "UZ" => "Usbekistan",
                          "VA" => "Vatikanstaat",
                          "VC" => "Saint Vincent und Grenadines",
                          "VE" => "Venezuela",
                          "VG" => "Virgin Islands (Britisch)",
                          "VI" => "Virgin Islands (U.S.)",
                          "VN" => "Vietnam",
                          "VU" => "Vanuatu",
                          "WF" => "Wallis und Futuna Islands",
                          "WS" => "Amerikanisch Samoa",
                          "YE" => "Jemen",
                          "YT" => "Mayotte",
                          "YU" => "Jugoslawien",
                          "ZA" => "Südafrika",
                          "ZM" => "Sambia",
                          "ZW" => "Zimbabwe");

        return array_search($name, $laender);
    }
}